---

- name: "Set cert local paths"
  set_fact:
    _localhost_cert_path: "{{ scylla_ssl.localhost_cert_path | default(inventory_dir + '/ssl/' + inventory_hostname + '/' + inventory_hostname + '.crt') }}"
    _localhost_cert_key_path: "{{ scylla_ssl.localhost_cert_key_path | default(inventory_dir + '/ssl/' + inventory_hostname + '/' + inventory_hostname + '.pem') }}"
    _localhost_ca_path: "{{ inventory_dir }}/ssl/ca/{{ scylla_cluster_name }}-ca.crt"
    _localhost_ca_key_path: "{{ inventory_dir }}/ssl/ca/{{ scylla_cluster_name }}-ca.pem"

- name: "Set cert remote paths"
  set_fact:
    _cert_path: "{{ scylla_ssl.cert_path }}/{{ _localhost_cert_path | basename }}"
    _cert_key_path: "{{ scylla_ssl.cert_path }}/{{ _localhost_cert_key_path | basename }}"
    _truststore_path: "{{ scylla_ssl.cert_path }}/truststore.crt"

- name: For every node, check if crt file exists
  stat:
    path: "{{ hostvars[item]['_localhost_cert_path'] }}"
  register: _node_crt
  loop: "{{ groups['scylla'] }}"
  delegate_to: localhost
  run_once: true

- name: For every node, check if key file exists
  stat:
    path: "{{ hostvars[item]['_localhost_cert_key_path'] }}"
  register: _node_key
  loop: "{{ groups['scylla'] }}"
  delegate_to: localhost
  run_once: true

- name: Set existence of crt and key as a single fact
  set_fact:
    _crt_and_key_exist: "{{ item.stat.exists }}"
  loop: "{{ _node_crt.results + _node_key.results }}"
  when: _crt_and_key_exist is not defined or _crt_and_key_exist == True
  run_once: true

- name: Check if at least one crt was provided
  set_fact:
    _some_crt_and_key_exist: "{{ item.stat.exists }}"
  loop: "{{ _node_crt.results + _node_key.results }}"
  when: _some_crt_and_key_exist is not defined or _some_crt_and_key_exist == False

- name: Check if CA exists
  block:
    - name: Check if CA crt file exists
      stat:
        path: "{{ _localhost_ca_path }}"
      register: _ca_crt
    - name: Check if CA key file exists
      stat:
        path: "{{ _localhost_ca_key_path }}"
      register: _ca_key
    - set_fact:
        _ca_crt_and_key_exist: "{{ _ca_crt.stat.exists|bool and _ca_key.stat.exists|bool }}"
  delegate_to: localhost
  run_once: true

- fail:
    msg: "You've provided crts only for a subset of your nodes. Either provide a CA that should be used for generating equivalent certificates for the others or delete the existing crts in order for the role to generate a new self-signed CA and certs for all the nodes"
  run_once: true
  when: not _crt_and_key_exist and _some_crt_and_key_exist and not _ca_crt_and_key_exist

- name: If crt and keys were not provided for all nodes and no CA was provided, generate a self-signed CA
  include_tasks: "{{ role_path }}/../shared-tasks/generate_certificate_and_key.yml"
  vars:
    - localhost_cert_path: "{{ _localhost_ca_path }}" 
    - localhost_cert_key_path: "{{ _localhost_ca_key_path }}"
    - cert_path: "{{ _truststore_path }}"
    - cert_key_path: "{{ _truststore_path }}" # Since we won't copy the CA key, let's set a dummy key path
    - cert_common_name: "{{ scylla_cluster_name }}.internal"
    - cert_basic_constraints: ['CA:TRUE']
    - cert_key_usage: ['keyCertSign']
    - copy_crt_to_remote: false
    - copy_key_to_remote: false
  when: _crt_and_key_exist == False

- name: Generate certificate signed by the local CA
  include_tasks: "{{ role_path }}/../shared-tasks/generate_certificate_and_key.yml"
  vars:
    - localhost_cert_path: "{{ _localhost_cert_path }}"
    - localhost_cert_key_path: "{{ _localhost_cert_key_path }}"
    - cert_path: "{{ _cert_path }}"
    - cert_key_path: "{{ _cert_key_path }}"
    - cert_common_name: "{{ inventory_hostname }}.{{ scylla_cluster_name }}.internal"
    - cert_basic_constraints: ['CA:FALSE']
    - cert_key_usage: ['digitalSignature', 'keyEncipherment']
    - ca_path: "{{ _localhost_ca_path }}"
    - ca_key_path: "{{ _localhost_ca_key_path }}"
    - copy_key_to_remote: true
  when: _crt_and_key_exist == False

- name: Copy truststore to the nodes
  block:
    - name: Check if truststore already exists in the remote host
      stat:
        path: "{{ _truststore_path }}"
      register: _truststore_file

    - name: Copy truststore
      copy:
        src: "{{ scylla_ssl.localhost_truststore_path }}"
        dest: "{{ scylla_ssl.cert_path }}/truststore.crt"
        owner: scylla
        group: scylla
        mode: '0644'
      become: true
      when: not _truststore_file.stat.exists and scylla_ssl.localhost_truststore_path is defined

    - name: Set _truststore_exists
      set_fact:
        _truststore_exists: "{{ _truststore_file.stat.exists or scylla_ssl.localhost_truststore_path is defined }}"

- name: Generate cqlshrc
  template:
    src: templates/cqlshrc.j2
    dest: "{{ inventory_dir }}/cqlshrc"
  delegate_to: localhost
  run_once: true
