---
- name: stop scylla
  service:
    name: scylla-server
    state: stopped
  become: true

- name: Remove /var/lib/scylla files
  shell: |
    sudo rm -rf /var/lib/scylla/data
    sudo find /var/lib/scylla/commitlog -type f -delete
    sudo find /var/lib/scylla/hints -type f -delete
    sudo find /var/lib/scylla/view_hints -type f -delete

- name: start scylla
  service:
    name: scylla-server
    state: started
  become: true
  #delegate_to: "{{ item }}"

# By default waits at most 7 hours for a node to start - bootstrapping and the corresponding streaming can take quite long
- name: Wait for CQL port
  wait_for:
    port: 9042
    #host: "{{ hostvars[item]['listen_address'] }}"
    host: "{{ listen_address }}"
    timeout: "{{ scylla_bootstrap_wait_time_sec }}"
  #delegate_to: "{{ item }}"
