---
- name: start scylla on {{ inventory_hostname }}
  service:
    name: scylla-server
    state: started
  throttle: 1
  become: true

# By default waits at most 7 hours for a node to start - bootstrapping and the corresponding streaming can take quite long
- name: Wait for CQL port on {{ rpc_address }}
  wait_for:
    port: 9042
    host: "{{ rpc_address }}"
    timeout: "{{ scylla_bootstrap_wait_time_sec }}"
  throttle: 1
